# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruise_name', models.CharField(max_length=200)),
                ('cruise_description', models.CharField(max_length=1000)),
                ('is_submitted', models.BooleanField()),
                ('terms_accepted', models.BooleanField()),
                ('cruise_approved', models.BooleanField()),
                ('last_edit_date', models.DateTimeField(max_length=200)),
                ('submit_date', models.DateTimeField(max_length=200)),
                ('cruise_leader_name', models.CharField(max_length=200)),
                ('cruise_leader_email', models.EmailField(max_length=254)),
                ('cruise_leader_contact', models.CharField(max_length=200)),
                ('student_participation_ok', models.BooleanField()),
                ('no_student_reason', models.CharField(max_length=200)),
                ('management_of_change', models.CharField(max_length=200)),
                ('safety_clothing_and_equipment', models.CharField(max_length=200)),
                ('safety_analysis_requirements', models.CharField(max_length=200)),
                ('equipment_description', models.CharField(max_length=200)),
                ('meals_on_board', models.CharField(max_length=500)),
            ],
        ),
    ]
