# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cruise', '0002_auto_20170627_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cruise.Event'),
        ),
    ]
