# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruise', '0003_auto_20170627_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeinterval',
            name='name',
            field=models.CharField(default='Unnamed event', max_length=50),
            preserve_default=False,
        ),
    ]
