# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruise_name', models.CharField(max_length=200)),
                ('cruise_description', models.CharField(max_length=1000)),
                ('is_submitted', models.BooleanField()),
                ('terms_accepted', models.BooleanField()),
                ('cruise_approved', models.BooleanField()),
                ('last_edit_date', models.DateTimeField()),
                ('submit_date', models.DateTimeField()),
                ('student_participation_ok', models.BooleanField()),
                ('no_student_reason', models.CharField(max_length=200)),
                ('management_of_change', models.CharField(max_length=200)),
                ('safety_clothing_and_equipment', models.CharField(max_length=200)),
                ('safety_analysis_requirements', models.CharField(max_length=200)),
                ('equipment_description', models.CharField(max_length=200)),
                ('meals_on_board', models.CharField(max_length=471)),
                ('cruise_leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cruise_leader', to=settings.AUTH_USER_MODEL)),
                ('cruise_owner', models.ManyToManyField(related_name='cruise_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CruiseDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_long_day', models.BooleanField()),
                ('description', models.CharField(max_length=471)),
                ('breakfast_count', models.PositiveSmallIntegerField()),
                ('lunch_count', models.PositiveSmallIntegerField()),
                ('dinner_count', models.PositiveSmallIntegerField()),
                ('overnight_count', models.PositiveSmallIntegerField()),
                ('cruise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reserver.Cruise')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserver.Cruise')),
            ],
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('time_before', models.DurationField()),
                ('is_active', models.BooleanField()),
                ('is_muteable', models.BooleanField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_on_board', models.BooleanField()),
                ('weight', models.FloatField()),
                ('size', models.CharField(max_length=200)),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserver.Cruise')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GeographicalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('cruise_day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reserver.CruiseDay')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('business_reg_num', models.PositiveIntegerField()),
                ('invoice_address', models.CharField(max_length=200)),
                ('accounting_place', models.CharField(max_length=200)),
                ('project_number', models.CharField(max_length=200)),
                ('invoice_mark', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserver.Cruise')),
            ],
        ),
        migrations.CreateModel(
            name='ListPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserver.InvoiceInformation')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_NTNU', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('identity_document_types', models.CharField(max_length=200)),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserver.Cruise')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('long_education_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('long_research_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('long_boa_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('long_external_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('short_education_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('short_research_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('short_boa_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('short_external_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_in_progress', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserver.Event')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_crew', models.BooleanField()),
                ('role', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('identity_document_types', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserver.Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebPageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='external_order_interval',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_order_interval', to='reserver.TimeInterval'),
        ),
        migrations.AddField(
            model_name='season',
            name='internal_order_interval',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_order_interval', to='reserver.TimeInterval'),
        ),
        migrations.AddField(
            model_name='season',
            name='season_interval',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_interval', to='reserver.TimeInterval'),
        ),
        migrations.AddField(
            model_name='invoiceinformation',
            name='default_invoice_information_for',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserver.Organization'),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='events',
            field=models.ManyToManyField(to='reserver.Event'),
        ),
        migrations.AddField(
            model_name='cruiseday',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserver.Event'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserver.Organization'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserver.Season'),
        ),
    ]
