# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0002_auto_20170628_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='cruise_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cruise_leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='cruise_owner',
            field=models.ManyToManyField(blank=True, null=True, related_name='cruise_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserver.Organization'),
        ),
        migrations.AlterField(
            model_name='cruiseday',
            name='cruise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserver.Cruise'),
        ),
        migrations.AlterField(
            model_name='cruiseday',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserver.Event'),
        ),
        migrations.AlterField(
            model_name='geographicalarea',
            name='cruise_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserver.CruiseDay'),
        ),
        migrations.AlterField(
            model_name='invoiceinformation',
            name='default_invoice_information_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserver.Organization'),
        ),
        migrations.AlterField(
            model_name='timeinterval',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserver.Event'),
        ),
    ]
