# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0003_auto_20170629_1039'),
        ('reserver', '0003_auto_20170628_1736'),
    ]

    operations = [
    ]
