# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0005_auto_20170630_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeinterval',
            name='event',
        ),
        migrations.RemoveField(
            model_name='season',
            name='external_order_interval',
        ),
        migrations.RemoveField(
            model_name='season',
            name='internal_order_interval',
        ),
        migrations.RemoveField(
            model_name='season',
            name='season_interval',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='external_order_event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_order_event', to='reserver.Event'),
        ),
        migrations.AddField(
            model_name='season',
            name='internal_order_event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_order_event', to='reserver.Event'),
        ),
        migrations.AddField(
            model_name='season',
            name='season_event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_event', to='reserver.Event'),
        ),
        migrations.AlterField(
            model_name='cruiseday',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserver.Event'),
        ),
        migrations.DeleteModel(
            name='TimeInterval',
        ),
    ]
