# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0007_auto_20170703_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='number_of_participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
