# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0010_auto_20170705_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cruise',
            old_name='cruise_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cruise',
            old_name='cruise_leader',
            new_name='leader',
        ),
        migrations.RenameField(
            model_name='cruise',
            old_name='cruise_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cruise',
            old_name='cruise_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='invoiceinformation',
            old_name='invoice_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='invoiceinformation',
            old_name='invoice_mark',
            new_name='mark',
        ),
        migrations.AddField(
            model_name='cruise',
            name='information_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cruise',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
