# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0011_auto_20170705_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceinformation',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
