# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 09:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0012_invoiceinformation_is_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='equipment_description',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='meals_on_board',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='name',
        ),
        migrations.AlterField(
            model_name='cruise',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cruiseday',
            name='is_long_day',
            field=models.BooleanField(default=True),
        ),
    ]
