# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0013_auto_20170706_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cruiseday',
            options={'ordering': ['event__start_time']},
        ),
    ]
