# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0014_auto_20170707_1446'),
        ('reserver', '0014_auto_20170707_1633'),
    ]

    operations = [
    ]
