# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0015_merge_20170708_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruiseday',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserver.Event'),
        ),
        migrations.AlterField(
            model_name='cruiseday',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserver.Season'),
        ),
    ]
