# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0015_merge_20170707_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cruise',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='cruise',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
