# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0016_auto_20170708_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruiseday',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserver.Event'),
        ),
    ]
