# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0017_auto_20170709_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cruise',
            options={'ordering': ['cruise_start']},
        ),
        migrations.AddField(
            model_name='cruise',
            name='cruise_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
