# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0017_auto_20170708_1435'),
        ('reserver', '0018_auto_20170710_0126'),
    ]

    operations = [
    ]
