# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0021_auto_20170718_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time']},
        ),
    ]
