# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0022_auto_20170719_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='management_of_change',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='no_student_reason',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='safety_analysis_requirements',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='safety_clothing_and_equipment',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='cruiseday',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='cruiseday',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cruiseday', to='reserver.Event'),
        ),
        migrations.AlterField(
            model_name='geographicalarea',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='season',
            name='external_order_event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_order', to='reserver.Event'),
        ),
        migrations.AlterField(
            model_name='season',
            name='internal_order_event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_order', to='reserver.Event'),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season', to='reserver.Event'),
        ),
    ]
