# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0023_auto_20170719_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name', 'start_time']},
        ),
    ]
