# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0024_auto_20170721_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('time_before', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_muteable', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='date',
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='is_muteable',
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='time_before',
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='title',
        ),
        migrations.AddField(
            model_name='cruise',
            name='equipment_description',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cruiseday',
            name='cruise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reserver.Cruise'),
        ),
        migrations.AlterField(
            model_name='cruiseday',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserver.Event'),
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='event',
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reserver.Event'),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reserver.EmailTemplate'),
        ),
    ]
