# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0026_emailnotification_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailnotification',
            old_name='recipient',
            new_name='recipients',
        ),
        migrations.AddField(
            model_name='cruiseday',
            name='destination',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
