# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0027_auto_20170728_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruiseday',
            name='destination',
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserver.Event'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='reserver.UserData'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserver.EmailTemplate'),
        ),
    ]
