# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0028_auto_20170804_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialized_dictionary', models.TextField()),
                ('needs_update', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='equipment_description',
        ),
        migrations.AlterField(
            model_name='cruiseday',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cruiseday', to='reserver.Event'),
        ),
    ]
